stages:
  - buildDev
  - deployDev

image: gitlab/dind
services:
  - docker:dind

buildDev:
  stage: buildDev
  tags:
    - ubuntu-runner
  only:
      - deployDev
  script:
    - docker login registry.gitlab.com -u "${dockerUserName}" -p "${dockerDeployToken}"
    - cp "${DEV_ENV}" .env
    - sh ./scripts/buildDevDocker.sh
    - docker logout
  
deployDev:
  stage: deployDev
  tags:
    - ubuntu-runner
  only:
      - deployDev
  script:
    - docker login registry.gitlab.com -u "${dockerUserName}" -p "${dockerDeployToken}" 
    - sh ./scripts/deployDevDocker.sh
    - docker logout    
