@DEV = http://localhost:8000/

@domain = {{DEV}}
@jsonContentType = application/json

### public route
GET {{domain}}health-check
Content-Type: {{jsonContentType}}

### private route
GET {{domain}}home
Content-Type: {{jsonContentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwiYWNjb3VudCI6Im1vY2tVc2VyIiwiaWF0IjoxNTk1MTYxNTI0fQ._19_avh34CO_-fYX64k66JU9w54rPuSzhgkkZFBj4S4

### Login username:password
POST {{domain}}auth
Content-Type: {{jsonContentType}}

{
  "account": "mockUser",
  "password": "a12345678"
}
